const issueInvoiceData = [
  {
    client_id: "D126930",
    customer: "APOLLO EXPORT MARELLA",
    DUE: "DUED",
    Status: "OPEN",
    invoice_no: "2023-104945",
    date_issued: "02-Oct-23",
    due_date: "01-Nov-23",
    pos: 589769,
    vessels: "M/V MARELLA EXPLORER",
    currency: "EUR",
    items: [
      {
        pos: "1",
        invoice: "",
        description: "test",
        unit: "pc",
        quantity: "1",
        unit_price: 10,
        currency: "Eur",
        total_price: "10",
      },
      {
        pos: "2",
        invoice: "",
        description: "test",
        unit: "pc",
        quantity: "1",
        unit_price: 10,
        currency: "Eur",
        total_price: "10",
      },
      {
        pos: "2",
        invoice: "",
        description: "test",
        unit: "pc",
        quantity: "1",
        unit_price: 10,
        currency: "Eur",
        total_price: "10",
      },
    ],
    amount: 569.97,
  },
  {
    client_id: "D126440",
    customer: "APOLLO EXPORT OCEANIA",
    DUE: "DUE",
    Status: "OPEN",
    invoice_no: "2022-104712",
    date_issued: "18-Oct-22",
    due_date: "17-Nov-22",
    pos: 547986,
    vessels: "M/V NAUTICA",
    currency: "EUR",
    items: [
      {
        pos: "2",
        invoice: "",
        description: "test",
        unit: "pc",
        quantity: "1",
        unit_price: 10,
        currency: "Eur",
        total_price: "10",
      },
      {
        pos: "2",
        invoice: "",
        description: "test",
        unit: "pc",
        quantity: "1",
        unit_price: 10,
        currency: "Eur",
        total_price: "10",
      },
      {
        pos: "2",
        invoice: "",
        description: "test",
        unit: "pc",
        quantity: "1",
        unit_price: 10,
        currency: "Eur",
        total_price: "10",
      },
    ],
    amount: 862.29,
  },
];
export default issueInvoiceData;
