const purchaseData = [
  {
    id: "",
    purchase_order_number: "1060",
    supplier: "TERMIN EINTREFFEND HAMBURG",
    supplierID: "123456",
    date_ofPO: "01-02-24",
    amount: "224,09",
    notes: "",
    due_date: "",
    invoice_date: "",
    invoice_number: "",
    file: "",
    history: [
      {
        pos: "1",
        item_number: "10640 31229 -414177",
        description: "TELLER TIEF 29 FAHNE FORM",
        unit: "pc",
        quantity: "6",
        unit_price: 13.09,
        currency: "Eur",
        total_price: "78,54",
      },
      {
        pos: "2",
        item_number: "10640 35474",
        description: "SCHALE OVAL FORM JADE",
        unit: "pc",
        quantity: "6",
        unit_price: 13.09,
        currency: "Eur",
        total_price: "78,54",
      },
      {
        pos: "3",
        item_number: "1064031229-414176",
        description: "SUPPENTASSE 0,25 FORM JADE",
        unit: "pc",
        quantity: "6",
        unit_price: 13.09,
        currency: "Eur",
        total_price: "78,54",
      },
    ],
    items: [
      {
        pos: "1",
        item_number: "10640 31229 -414177",
        description: "TELLER TIEF 29 FAHNE FORM",
        unit: "pc",
        quantity: "6",
        unit_price: 13.09,
        currency: "Eur",
        total_price: "78,54",
      },
      {
        pos: "2",
        item_number: "10640 35474",
        description: "SCHALE OVAL FORM JADE",
        unit: "pc",
        quantity: "6",
        unit_price: 13.09,
        currency: "Eur",
        total_price: "78,54",
      },
      {
        pos: "3",
        item_number: "1064031229-414176",
        description: "SUPPENTASSE 0,25 FORM JADE",
        unit: "pc",
        quantity: "6",
        unit_price: 13.09,
        currency: "Eur",
        total_price: "78,54",
      },
    ],
  },
  {
    id: "",
    purchase_order_number: "1060",
    supplier: "Y",
    supplierID: "123456",
    date_ofPO: "01-02-24",
    amount: "224,09",
    notes: "",
    due_date: "",
    invoice_date: "",
    invoice_number: "",
    file: "",
    history: [
      {
        pos: "1",
        item_number: "10640 31229 -414177",
        description: "TELLER TIEF 29 FAHNE FORM",
        unit: "pc",
        quantity: "6",
        unit_price: 13.09,
        currency: "Eur",
        total_price: "78,54",
      },
      {
        pos: "2",
        item_number: "10640 35474",
        description: "SCHALE OVAL FORM JADE",
        unit: "pc",
        quantity: "6",
        unit_price: 13.09,
        currency: "Eur",
        total_price: "78,54",
      },
      {
        pos: "3",
        item_number: "1064031229-414176",
        description: "SUPPENTASSE 0,25 FORM JADE",
        unit: "pc",
        quantity: "6",
        unit_price: 13.09,
        currency: "Eur",
        total_price: "78,54",
      },
    ],
    items: [
      {
        pos: "1",
        item_number: "10640 31229 -414177",
        description: "TELLER TIEF 29 FAHNE FORM",
        unit: "pc",
        quantity: "6",
        unit_price: 13.09,
        currency: "Eur",
        total_price: "78,54",
      },
      {
        pos: "2",
        item_number: "10640 35474",
        description: "SCHALE OVAL FORM JADE",
        unit: "pc",
        quantity: "6",
        unit_price: 13.09,
        currency: "Eur",
        total_price: "78,54",
      },
      {
        pos: "3",
        item_number: "1064031229-414176",
        description: "SUPPENTASSE 0,25 FORM JADE",
        unit: "pc",
        quantity: "6",
        unit_price: 13.09,
        currency: "Eur",
        total_price: "78,54",
      },
    ],
  },
];
export default purchaseData;
